# Generated by Django 3.2.3 on 2021-05-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=255)),
                ('court_name', models.CharField(max_length=255)),
                ('ruling_type', models.CharField(blank=True, max_length=255)),
                ('case_type', models.CharField(blank=True, max_length=255)),
                ('issue_category', models.CharField(blank=True, max_length=255)),
                ('ruling_text', models.TextField()),
                ('case_title', models.CharField(max_length=255)),
                ('related_case', models.CharField(blank=True, max_length=255)),
                ('working_condition', models.CharField(blank=True, default='', max_length=255)),
                ('disease_type', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
    ]
